### PR TITLE
Update apps.json

### PR DESCRIPTION
**Pull request by bmaluijb**
Add Podhome App, which is a podcast player app from Podhome (coming to an app store near you in 2025)

### CODE REVIEW

**Comment by johnspurlock** [comment]
Thanks - do you have an example Android ua string?

**Comment by bmaluijb** [comment]
Sure: "Podhome App/1.0 (Linux; Android 10; SM-G960F Build/QP1A.190711.020) ExoPlayerLib/2.10.4"

**Comment by johnspurlock** [comment]
Great, can you include it in the examples array?

**Comment by johnspurlock** [comment]
Thanks!

**Pull request merged**
