### PR TITLE
Added WynkMusic to apps.json

### PR DESCRIPTION
**Pull request by pbaveja**
Wynk Music (https://wynk.in/podcasts) is missing from this. Adding the categorisation inside app.json with this PR

### CODE REVIEW

**Comment by johnspurlock** [comment]
thanks! can you add that info url in an `urls` array as part of the entry?

Also, is there an iOS example?

**Comment by johnspurlock** [comment]
👋 @pbaveja can you add that info url in an urls array as part of the entry?

Also, is there an iOS example user agent string?

**Comment by pbaveja** [comment]
Hey @johnspurlock, I've added the info URL. 

I couldn't find an iOS useragent unfortunately

**Comment by johnspurlock** [comment]
Ok I merged it, but would like to have the iOS user-agent too.  I can't install that app on an iPhone in my region.  If you can, let me know and I'll walk you through how to determine it.

**Pull request merged**
