### PR TITLE
chore: add twipe to user agent

### PR DESCRIPTION
**Pull request by MatthiasDh**

### CODE REVIEW

**Comment by johnspurlock** [comment]
What app is this?  Can you include links to the app in the google/apple app store in the `urls` field?

I haven't seen these user agents before, would be nice to be able to confirm them by playing something in a public app.

**Comment by MatthiasDh** [comment]
@johnspurlock I added the website to the urls, Twipe provides a white label app for news publishers, they don't have an app directly on the stores.

However have multiple clients that do have apps on the stores. Ex The Telegraph, Daily Mail, ...

**Comment by MatthiasDh** [comment]
@johnspurlock any feedback to get this merged in? Thanks!

**Comment by johnspurlock** [comment]
Merged, thanks!

**Comment by MatthiasDh** [comment]
Thank you! :)

**Pull request merged**
