### PR TITLE
Add the Castos Web Player to the referrers list

### PR DESCRIPTION
**Pull request by jtolj**
Hey @johnspurlock,

Thanks for your incredible work on this list. 

I just added (hopefully correctly) the Castos Web Player to the referrers.

Also please let me know if there's anything I can do to help out with this more generally. I'm the engineering lead at Castos and this resource has been really helpful.

### CODE REVIEW

**Review by johnspurlock — COMMENTED** [review]
Hi Jesse, can you remove the pathname from the pattern?  Most browsers/sites just send the origin down in the referer header these days.

ie remove the "(player|playlist-player)/" bit at the end

**Comment by jtolj** [comment]
> Hi Jesse, can you remove the pathname from the pattern?  Most browsers/sites just send the origin down in the referer header these days.
> 
> 
> 
> ie remove the "(player|playlist-player)/" bit at the end
> 
> 

👍 will update tomorrow.

**Comment by jtolj** [comment]
@johnspurlock 

Updated, thanks!

**Comment by johnspurlock** [comment]
thanks!

**Pull request merged**
