### PR TITLE
Update apps.json

### PR DESCRIPTION
**Pull request by jamescridland**
Sprewell app. Seen 46 times in one day in OP3

### CODE REVIEW

**Comment by johnspurlock** [comment]
Do you have an Android example?

**Comment by jamescridland** [comment]
I didn’t see one.

**Comment by johnspurlock** [comment]
Ok, I'll recharge an Android phone, install the app, and use the OP3 hits api to see what it sends

This is much easier to do now that hits are available sooner and can be sorted in reverse chron with the new `desc` param

https://op3.dev/api/1/hits?format=json&token=preview07ce&hashedIpAddress=current&desc

**Comment by johnspurlock** [comment]
Ok, the Android app uses `just_audio/1.0.68 (Linux;Android 12) ExoPlayerLib/2.18.7` for streaming and `Mozilla/5.0...` for downloading 🙄

It did prompt me to fix the classification of Just Audio to library, not app: https://github.com/opawg/user-agents-v2/commit/38e1d4f5091dbc5e19f92f9629e51738f9741ac6

**Pull request merged**
